### ISSUE TITLE
Deployment to AKS does not support "PodDisruptionBudget"

### ISSUE THREAD

**Issue by cliftonz1** [Dynatrace/dynatrace-operator#1009]
The error we are getting is the following:
```
unable to recognize "https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.7.2/kubernetes.yaml": no matches for kind "PodDisruptionBudget" in version "policy/v1"
error validating "https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.7.2/kubernetes.yaml": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "seccompProfile" in io.k8s.api.core.v1.SecurityContext;
```
with the command:
```
kubectl apply -f https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.7.2/kubernetes.yaml
```

**Comment by luhi-DT** [comment]
Hi,what Kubernetes version do you have?

**Comment by cliftonz1** [comment]
It looks like we are using v1.18.10 which is the latest that AKS supports.

**Comment by luhi-DT** [comment]
This Kubernetes version is not supported by the Dynatrace Operator v0.7.2, this also explains why you get the error above, since PodDisruptionBudget is GA since 1.21. According to this table [here](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions#aks-kubernetes-release-calendar) AKS is of course supporting higher versions. Thanks!

**Comment by cliftonz1** [comment]
Thank for this, I will take a look at this with my team.
