### ISSUE TITLE
[FR] Add support for PodDisruptionBudget for Operator

### ISSUE THREAD

**Issue by pierluigilenoci** [Dynatrace/dynatrace-operator#1033]
To date, the Helm Chart does not support the [PDB](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) for the [Operator](https://github.com/Dynatrace/dynatrace-operator/tree/master/config/helm/chart/default/templates/Common/operator).

It is only supported for the [webhook](https://github.com/Dynatrace/dynatrace-operator/blob/master/config/helm/chart/default/templates/Common/webhook/poddisruptionbudget-webhook.yaml).

**Comment by luhi-DT** [comment]
Hi, maybe to understand your request a little bit more, what is your use case in order to have a PDB specified for the operator? Thanks!

**Comment by pierluigilenoci** [comment]
A PDB is required in case you need to install applications in HA mode.

Considering the number of replicas for the `operator` it is hard coded and is [`1`](https://github.com/Dynatrace/dynatrace-operator/blob/master/config/helm/chart/default/templates/Common/operator/deployment-operator.yaml#L27) I wonder if it is possible to run it in a higher number of replicas. If so, I would also ask for the ability to configure the number of replicas with the Helm Chart.

**Comment by luhi-DT** [comment]
Its not possible to run multiple operator replicas at the same time, as there can only be one leader at a time more here: https://docs.openshift.com/container-platform/4.8/operators/operator_sdk/osdk-leader-election.html therefore autoscaling and PDB is not necessary. Thanks!

**Comment by pierluigilenoci** [comment]
@luhi-DT so are you telling me that there is no way to run the operator in HA mode?

**Comment by luhi-DT** [comment]
Currently this is not possible no, however if you feel your issue should be further addressed please use [Dynatrace community](https://community.dynatrace.com/) rather than Github. This helps our team consolidate, rank, and prioritize important input like yours.

Please search for similar requests, collaborate, and ask questions using the link above. Remember to add the labels "kubernetes" and "dynatrace-operator" to help get the attention you deserve.

Thanks for your help!
