### ISSUE TITLE
Re-using the activegate

### ISSUE THREAD

**Issue by hbuckle** [Dynatrace/dynatrace-operator#1083]
We currently have active gates deployed on virtual machines to provide Azure monitoring. Is there any reason not to just enable the Azure module on the active gate deployed by dynatrace-operator and remove the virtual machine deployments?

**Comment by meik99** [comment]
The Azure module is currently not supported when using the containerized ActiveGate.
A list of modules that are supported by the containerized ActiveGate can be found here: https://www.dynatrace.com/support/help/shortlink/activegate-capabilities

**Comment by luhi-DT** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Feature request".

Dynatrace reviews feature requests in the [Dynatrace community](https://community.dynatrace.com/) rather than Github. This helps our team consolidate, rank, and prioritize important input like yours.

Please search for similar requests, collaborate, and ask questions using the link above. Remember to add the labels "kubernetes" and "dynatrace-operator" to help get the attention you deserve.

Thanks for your help!
