### ISSUE TITLE
Could operator mark the initContainer fail when OneAgent installation is failed?

### ISSUE THREAD

**Issue by KeaneYu** [Dynatrace/dynatrace-operator#1121]
The case is we are using application-only injection, sometimes the init-container will fail to install OneAgent (like below capture), and it will be masked to **not** fail the container. 
Our questions is, is there any configuration to fail the container? 
We want this condition to be failed and then retry, otherwise their application pod can start but no OneAgent, we don't want such result.
![image](https://user-images.githubusercontent.com/14102746/188096009-c150bc29-4495-4e5b-a1c7-d76b1b4b8999.png)

**Comment by luhi-DT** [comment]
Hi, there is an annotation for that, which can be set on a PodLevel, so the pod will fail if the init Container has some errors. `oneagent.dynatrace.com/failure-policy="fail"` . However the default is to continue silently in order to ensure your workloads are not affected by any error which could happen in the initContainer.

**Comment by KeaneYu** [comment]
I think suppressing the failure may not be a good choice. Even if the workload can work without OneAgent. We will lost the monitor capability without noticing.

**Comment by luhi-DT** [comment]
We made that decision on purpose, since we dont want to fail applications, because something is going wrong with our injection. However the above mentioned flag gives you the possibility to change that behaviour :)
