### ISSUE TITLE
webhook pod/container ephemeral-storage limit too low

### ISSUE THREAD

**Issue by eldis80** [Dynatrace/dynatrace-operator#1123]
The ephemeral-storage limit seems to be too low for webhook container. The pod gets evicted every few hours because it exceeds the ephemeral storage limit. This is happening with operator v0.8.2

After increasing the ephemeral-storage limit from 10MB to 50MB the pods get evicted more infrequently but it looks like the storage usage is constantly increasing until any limit.

**Comment by luhi-DT** [comment]
Hi, we are aware that it can happen that the operator pods get evvicted, because in certain cases it writes to much log information, so the ephemeral storage limit is reached, however that limit can be removed from the operator/webhook deployment completely in such cases and does not have an influence on the functionality. We will add a fix/improvement for that with 0.9.0. Thanks!

**Comment by rteeling** [comment]
I've been seeing this issue in my clusters as well.

The 0.9.0 chart has the configurable ephemeral storage, but has anybody identified what is causing the limit to blow out?

**Comment by luhi-DT** [comment]
Hi, yes we removed default limits with 0.9.0 and made them configurable. We identified the logs written by the various operator components to fill up the ephemeral storage. So it was no actual storage leak.
