### ISSUE TITLE
Multiple LD_PRELOAD instances

### ISSUE THREAD

**Issue by adamrehor** [Dynatrace/dynatrace-operator#1201]
Hello,
We have an application that currently uses LD_PRELOAD and when Dynatrace injects its own LD_PRELOAD it is causing application crashes. Is there currently any way to have Dynatrace add the LD_PRELOAD path to the existing LD_PRELOAD or some other type of workaround for this? 
 
`      - name: LD_PRELOAD                                                          # <------  app needs this`
`        value: /usr/lib64/libnss_wrapper.so`
 `...`
`       - name: LD_PRELOAD                                                          # <------  Dynatrace injected this`
`        value: /opt/dynatrace/oneagent-paas/agent/lib64/liboneagentproc.so `

**Comment by d41k4n** [comment]
I think we worked around this by modifying the image with a start script that takes any pre-defined value for LD_PRELOAD and appends the required path to it before invoking the actual executable.

**Comment by adamrehor** [comment]
Hi,
I wanted to follow up on this issue. Will this feature be added in any of the upcoming Operator versions? Or is it on the roadmap for the Operator?

**Comment by luhi-DT** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Feature request".

Dynatrace reviews feature requests in the [Dynatrace community](https://community.dynatrace.com/) rather than Github. This helps our team consolidate, rank, and prioritize important input like yours.

Please search for similar requests, collaborate, and ask questions using the link above. Remember to add the labels "kubernetes" and "dynatrace-operator" to help get the attention you deserve.

Thanks for your help!
