### ISSUE TITLE
How do you specify which mode the operator should run in using helm?

### ISSUE THREAD

**Issue by erickertzvfc** [Dynatrace/dynatrace-operator#1212]
I'm trying to use Helm to install the operator and I'm unsure how to change the values here:

https://github.com/Dynatrace/dynatrace-operator/blob/v0.8.2/config/helm/chart/default/values.yaml

to switch between classic full-stack injection, cloud-native full-stack injection, and automatic application-only injection on Kubernetes. It's also unclear to me on how to do this in the docs https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/get-started-with-kubernetes-monitoring/set-up-k8s-monitoring-helm

Thanks!

**Comment by luhi-DT** [comment]
Hi, as you might have missed that the helm chart changed since v0.7.0. See more here https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/get-started-with-kubernetes-monitoring/set-up-k8s-monitoring-helm#migrate 

With the introduction of that change, the DynaKube is not part of the helm chart anymore, the helm chart is only used for deploying the operator and its compontents (operator/webhook/csi-driver). The actual configuration of the mode you want to use is done in a seperate step (by applying the CR). Documented here: https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/get-started-with-kubernetes-monitoring/set-up-k8s-monitoring-helm#migrate:~:text=Follow%20steps%204%20to%209%20from%20Get%20started%20with%20Kubernetes/OpenShift%20monitoring.
