### ISSUE TITLE
Dynatrace for app-only: the initContainer install-oneagent not supports no_proxy

### ISSUE THREAD

**Issue by NatanAOliveira** [Dynatrace/dynatrace-operator#1259]
We are trying to upgrade our dynatrace operator to v0.9.0 but now there’s no way to set no_proxy to bypass the installer url.

**Comment by NatanAOliveira** [comment]
Our current version is 0.4.2

**Comment by luhi-DT** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Feature request".

Dynatrace reviews feature requests in the [Dynatrace community](https://community.dynatrace.com/) rather than Github. This helps our team consolidate, rank, and prioritize important input like yours.

Please search for similar requests, collaborate, and ask questions using the link above. Remember to add the labels "kubernetes" and "dynatrace-operator" to help get the attention you deserve.

Thanks for your help!
