### ISSUE TITLE
Add support for certificate injection in OpenShift

### ISSUE THREAD

**Issue by simonstumpf** [Dynatrace/dynatrace-operator#1274]
Hi all,

We're deploying the dynatrace-operator on several of our OpenShift clusters. 
Since these cluster are in different networks they need different trustedCAs. 
However there is this quiet useful option in OpenShift to create a ConfigMap which holds all user-provided and system CA certificates which are then stored in a single bundle (see [OpenShift docs](https://docs.openshift.com/container-platform/4.10/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki).

Would it be possible in a future operator release to have this setup supported? It would really help all of the others customs which use Dynatrace in a OpenShift setup.

**Comment by luhi-DT** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Feature request".

Dynatrace reviews feature requests in the [Dynatrace community](https://community.dynatrace.com/) rather than Github. This helps our team consolidate, rank, and prioritize important input like yours.

Please search for similar requests, collaborate, and ask questions using the link above. Remember to add the labels "kubernetes" and "dynatrace-operator" to help get the attention you deserve.

Thanks for your help!
