### ISSUE TITLE
Enable events and prometheus to automatically be enabled on new clusters

### ISSUE THREAD

**Issue by hbouma1** [Dynatrace/dynatrace-operator#1302]
I see that this has been talked about before, https://github.com/Dynatrace/dynatrace-operator/issues/884, where people would like to have the Prometheus integration and Event ingestion automatically turned on. The previous reply stated that this was going to be worked on, and I wanted to check if that was still the case, or do we need to manually script out to fix the Dynatrace Kubernetes integration every time a new cluster is stood up?

**Comment by luhi-DT** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Feature request".

Dynatrace reviews feature requests in the [Dynatrace community](https://community.dynatrace.com/) rather than Github. This helps our team consolidate, rank, and prioritize important input like yours.

Please search for similar requests, collaborate, and ask questions using the link above. Remember to add the labels "kubernetes" and "dynatrace-operator" to help get the attention you deserve.

Thanks for your help!

**Comment by hbouma1** [comment]
Thank you. I have submitted a product idea for this as I couldn't find any that already asked for this feature.

https://community.dynatrace.com/t5/Dynatrace-product-ideas/Dynatrace-Operator-yaml-to-turn-on-Events-ingestion-and/idi-p/198079
