### ISSUE TITLE
[Feature] Activegate services adopted ingress exposed  

### ISSUE THREAD

**Issue by JayChanggithub** [Dynatrace/dynatrace-operator#1340]
Hi support, 

We'd like to adopt  ingress to agent backend service which `activegate`. However we got error like `"[warn] 84139#84139: *11134419 upstream sent more data than specified in "Content-Length" header while reading response header from upstream"`. Have anything apporach to do these?

**Comment by luhi-DT** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Support request".

Dynatrace responds to requests like these via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.

Thanks for your help!
