### ISSUE TITLE
Dynatrace operator in operator hub not automatically updating

### ISSUE THREAD

**Issue by gjerdrun** [Dynatrace/dynatrace-operator#1484]
**Describe the bug**
After 0.10.2 was released it does not automatically upgrade from 0.10.1 to 0.10.2. The Update channel is "Alpha" and update approval is set to "Automatic"

This also happened from 0.9.X to 0.10.1 as well.

Running on Openshift 4.10.41/47 (multiple clusters with same issue)

The 0.10.2 update is available in operator hub as a "Certified" update.

Even if i change the Update approval to manual i do not get an option to upgrade.
Inn the case from 0.9.X to 0.10.1 i had to uninstall the operator and install it again, but this is not good since it then requires to reinstall the dynakube.
![Screenshot 2023-01-19 at 13 53 22](https://user-images.githubusercontent.com/83689917/213448154-79c8efa6-8b89-423e-9b20-cd40c6df3959.png)
![Screenshot 2023-01-19 at 13 54 08](https://user-images.githubusercontent.com/83689917/213448162-eaec947c-56ce-44eb-b07b-cd90f8c2b55d.png)

**Comment by luhi-DT** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Support request".

Dynatrace responds to requests like these via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.

Thanks for your help!
