### ISSUE TITLE
Process/container restart post deploying OA operator 

### ISSUE THREAD

**Issue by pravindandra** [Dynatrace/dynatrace-operator#164]
This is more of a question than an issue. I tried both automated way of deploying OA operator from the Dynatrace Hub on the UI and also manual way using the documentation [doc](https://www.dynatrace.com/support/help/shortlink/kubernetes-manage-helm)

Why was process/container restart not required when tried the automated way? Is the code taking care of it?

**Comment by DTMad** [comment]
Hey @pravindandra 
What exactly do you mean by "process/container restart"?
You mean the warning displayed in the Dynatrace UI?

If you mean this the reason is the following:
The OneAgent needs to run before your application to be able to properly inject. This is a known limitation (see https://www.dynatrace.com/support/help/shortlink/oneagent-docker#limitations - last point).
If this only happened for you with the automated way this was just the matter of timing ;)
