### ISSUE TITLE
Security concerning on mounting the whole root filesystem / with read/write permissions into container

### ISSUE THREAD

**Issue by nature502** [Dynatrace/dynatrace-operator#1882]
The oneAgent pod mounts the whole root filesystem / with read/write permissions. It is therefore possible to modify the host OS from within  container. Such changes might cause security implications that could put the host in compromised state. Is there any way to get rid of this ?
Respective setting in the config.json:
    **{
      "destination": "/mnt/root",
      "type": "bind",
      "source": "/",
      "options": [
        "rbind",
        "rprivate",
        "ro"
      ]
    }**

**Comment by luhi-DT** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Support request".

Dynatrace responds to requests like these via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.

Thanks for your help!
