### ISSUE TITLE
ClusterRole

### ISSUE THREAD

**Issue by Sly555** [Dynatrace/dynatrace-operator#1921]
Hi !
**Describe the bug**

The ClusterRoles and ClusterRoleBindings dynatrace-activegate and dynatrace-dynakube-oneagent-privileged are defined in both yaml files  : dynatrace.yaml and dynatrace-csi.yaml. In 0.11.2 it was't the case.

dynatrace-dynakube-oneagent-unprivileged is giving privileged access ...

**To Reproduce**
check dynatrace.yaml and dynatrace-csi.yaml

**Expected behavior**
Remove duplicated clusterrole names in one of the two files. 
The clusterrole dynatrace-dynakube-oneagent-unprivileged should not gave privileged acces, or you could change the name.

**Screenshots**
![image](https://github.com/Dynatrace/dynatrace-operator/assets/77111210/f004083b-3397-4c89-9ee9-f16e7a787ccc)

**Additional context**
Thanks

**Comment by 0sewa0** [comment]
this is fixed in main: https://github.com/Dynatrace/dynatrace-operator/pull/1881

but those service accounts are really old, that is why their names are confusing (there use to be a reason for having multiple service accounts, but no longer)

and the privileged SCC is "needed" because we only want  to use built in SCCs (custom ones just caused confusion), AND the privileged SCC is the only built-in SCC that allows csi volumes. (maybe in openshift 4.13 this changes)

**Comment by Sly555** [comment]
Hi 

Thanks for the fast answer !

For the duplicated scc in yaml files I made a mistake in the file names.

https://github.com/Dynatrace/dynatrace-operator/releases/download/0.12.0/openshift.yaml 
and 
https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.12.0/openshift-csi.yaml

The ClusterRoles and ClusterRoleBindings 

- dynatrace-activegate 
- dynatrace-dynakube-oneagent-privileged 

are defined in both yaml files.
