### ISSUE TITLE
Dynatrace operator does not notice when oneAgent fails to start up.

### ISSUE THREAD

**Issue by Jaykul** [Dynatrace/dynatrace-operator#1942]
**Describe the bug**

As I said in #1940, v0.12.0 is giving us problems and the oneAgent fails to start.

However, the dynatrace-operator does not _care_ that there are no oneAgents working. In it's logs, it just keeps reporting: 

```json
{"level":"info","ts":"2023-07-11T21:19:29.714Z","logger":"dynakube-oneagent","msg":"reconciling OneAgent"}
{"level":"info","ts":"2023-07-11T21:19:29.718Z","logger":"dynakube-oneagent","msg":"configMap unchanged","name":"dynatrace-sl1-oneagent-connection-info","namespace":"dynatrace"}
{"level":"info","ts":"2023-07-11T21:19:29.718Z","logger":"dynakube-oneagent","msg":"oneagent instance statuses reconciled"}
{"level":"info","ts":"2023-07-11T21:19:29.718Z","logger":"dynakube-oneagent","msg":"reconciled classic_fullstack"}
```

**To Reproduce**

See the steps in #1940 -- basically, do a clean install with v0.12.0

**Expected behavior**

When the DaemonSet pods are all in "FailedCreate" state, I would expect the operator to notice this and try to correct it.

If your operator does not monitor the actual state of the activeGate and oneAgents and try to correct it, I would rather just have a helm chart with a values.yaml in place of the "dynakube" resource.

That is, an operator needs to do more than what Helm charts can do -- otherwise, you're just **wasting our resources** to run an extra container (the operator, to be clear) merely to run Helm charts (which I already have to do to install the operator!).

**Comment by luhi-DT** [comment]
Hi, 

it's a little bit tricky when it comes down to operators creating RBAC resources and everything that the product the operator manages needs. Giving the operator the power to create ClusterRoles, ServiceAccounts etc. basically grants him the power to do everything. While one might think this is what an operator is supposed to do, another customer will say that this is not feasible in their environment, as they will not grant an operator the permission to create RBACs. Therefore we have decided to roll out the operators RBACs during installation in order to not hide what permissions are needed in code.

Not having the ClusterRole setup in the cluster properly, will lead to an error like that, which is for sure not nice, but trade off we have to make in order to not have RBACs managed by the operator, but as a manifests instead.

Regarding the feature set that the operator provides in classicFullStack. There are a lot of features that a helm-chart can not deliver. Just as some examples -> automatic updates of oneAgents, rollout of an activeGate, automatic api monitoring, etc..


However if you have additional input please feel free and very welcomed to reach out to our Product Team via the [Dynatrace Community](https://community.dynatrace.com/), there you can directly discuss your ideas and inputs with them. 

Thanks!
