### ISSUE TITLE
customProperties settings for ActiveGate are not reconciled and changes are not deployed

### ISSUE THREAD

**Issue by 163a** [Dynatrace/dynatrace-operator#2018]
**Describe the bug**
Commenting out the customProperties doesn't remove the settings for ActiveGate. Changing the customProperties to a new value doesn't update the existing ActiveGate.
This is a problem with the reconciler.
It is NOT EVEN possible to get the customProperties to update by manually deleting the ActiveGate pod. Upon re-initialisation, it seems to persist the previous custom.properties, even though I changed it in the CR dynakube.

I will have to completely blast the namespace, since a naive attempt to remove persistent storage by manually deleting the statefulset result in a total loss of the ActiveGate and the Operator could not recover it as it doesn't know it's gone:
```
$ kd delete statefulset dynakube-custom-activegate
statefulset.apps "dynakube-custom-activegate" deleted
$ kd get pods
NAME                                 READY   STATUS        RESTARTS   AGE
dynakube-custom-activegate-0         1/1     Terminating   0          5m34s
...
$ kd apply -f cr.yaml 
dynakube.dynatrace.com/dynakube-custom unchanged
$ kd get statefulset
No resources found in dynatrace namespace.
```

**To Reproduce**
1. Change CR.yaml to set customProperties for ActiveGate
2. Apply the cr.yaml `kd apply -f cr.yaml` where `kd` is an alias for the dynatrace namespace

An example:
(where the custom DNS entry point was commented out, but nothing changed for the existing ActiveGate)
```    # Optional: Add a custom properties file by providing it as a value or reference it from a secret
    # If referenced from a secret, make sure the key is called 'customProperties'
    #
    customProperties:
      value: |
         [com.compuware.apm.webserver]
         ssl-protocols=TLSv1.3
    #    [connectivity]
    #    dnsEntryPoint=https://dynakube-custom-activegate.dynatrace.svc.cluster.local:443/communication
```

**Expected behavior**
ActiveGate custom properties gets updated when re-configuring the cr.yaml dynakube.
It should be the case that custom.properties file gets re-created from the settings in the dynakube and the ActiveGate restarted.

**Additional context**
Operator 0.12.1

**Comment by luhi-DT** [comment]
Hi, i just tested your mentioned behaviour and everything seems to work fine in my case.

**Tested Cases**

1.  Change custom properties in an existing Dynakube -> activeGate is restarted with proper values
2.  Commented out customer properties completely -> activeGate is restarted without any custom properties
3.  Change customProperties from empty value to some value (ssl-protocol) -> activeGate was restarted with ssl-protocol

Therefore I would suggest you to open a new ticket at our official support as this seems like an issue with your environment rather than a general issue: [Dynatrace ONE support](https://support.dynatrace.com/)

Thanks for your understanding!
