### ISSUE TITLE
Feature request: Install DynaKube using a Helm Chart in the same manner that the Operator is installed via Helm.

### ISSUE THREAD

**Issue by jhd235** [Dynatrace/dynatrace-operator#3048]
Installing Dynatrace Operator currently involves installing Operator via Helm chart and then installing DynaKube via kubectl.

Why DynaKube cannot be installed via Helm Chart in the same manner that the Operator is installed via Helm.

**Comment by luhi-DT** [comment]
Hi, the problem is that helm v3 has some downsides, when it comes down to handling and maintaining CRDs. The problem is that you basically have 2 different options to install CRDs. 

1. Place it in the crds folder, this folder will be applied before all other ressources, however this folder will only be applied during the first install, not during upgrades, which does not allow updates to CRDs

2. Have it as a normal manifests -> this allows upgrades to CRDs, however this approach only applies the CRDs during the process of applying all other manifests aswell -> If you know have a custom ressource (instance of this CRD) and also want to apply it -> it may fail as you cannot predict which manifest will be applied first

As we opted for the 2nd approach, we will not be able to also deploy a DynaKube CR in the same step.

More info: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

Thanks,
Lukas
