### ISSUE TITLE
Activegate is consuming 20 GB of memory on Openshift cluster

### ISSUE THREAD

**Issue by ashishibm11** [Dynatrace/dynatrace-operator#467]
We have seen high memory utilization for dynakube-activegate pod i.e. 20 GB of memory. Is there any specific reason for this kind of behavior for dynakube-activegate?

**Comment by d41k4n** [comment]
How big is your cluster (nodes, workloads, namespaces)?

Ours has 79 nodes, ~2200 workloads and 392 namespaces and we currently use a memory limit of 1GiB which works fine most of the time. 

However, we experienced one particular issue where the memory consumption suddenly went through the roof with warnings like

`WARNING [<collector>] [<platform>, MemoryTrackerImpl] Heap memory shortage detected: 91% memory usage in memory pool 'CMS Old Gen'`

spamming the log. We were never able to determine the root cause of that... The really bad thing is it went completely unnoticed for several days and caused complete K8s monitoring metric data loss as there were no built-in alerts of any kind and neither the pod's liveness or readiness probes seemed to be bothered by this so the pod didn't get auto-killed.... The workaround was simply to kill the AG pod manually.... Luckily this happened only once so far...

We keep seeing occasional warnings as the one above although without any noticeable negative effects so currently we're sticking to 1GiB and created custom events for alerting on missing metric data and high heap memory consumption...

**Comment by ashishibm11** [comment]
We are having 6 nodes , approx 500 pods running in 100 namespaces , still memory consumption is really high for dynakube-activegate agent. We need some idea how we can debug and and resolve this concern.

**Comment by d41k4n** [comment]
What will happen if you set the pod's memory limit to the "default" 1GiB? 

Did you ever contact support about your issue?

Note that in our case support told us that a memory limit of 1GiB should usually be "more than enough"... so 20GB seems totally unreasonable and I wonder why you decided to set a memory limit that allowed for such high memory consumption in the first place,...

Also, I suppose increasing the memory limit for no actual reason will automatically cause the JVM to adapt its memory pool sizes accordingly and possibly grab all the memory it can even if it would be running fine (or even better) with just 1GiB...

**Comment by luhi-DT** [comment]
Hi, if you are running the Activegate without any limits applied it can use up to 50% of the available resources, which is in your case as high as 20gb i guess. We're also aiming to provide sizing guidline and built-in defaults as soon as possible. In the meanwhile I would suggest to set memory limits on your own in order to decrease usage of memory. We suggest to giving 1GB to AG and see on sfm metrics how it behaves.

**Comment by ulukitkan** [comment]
any changes expected for this AG mem behaviour in 0.4.0 ?

**Comment by luhi-DT** [comment]
Not in 0.4.0 since it was released today, we are still working on providing sizing guideline and defaults as I said. But anyway, you can set limits on your own at anytime

**Comment by alexfokjob** [comment]
any update? same issue when using activegate on AWS EKS

**Comment by meik99** [comment]
The conclusion is, that when facing this issue using the ActiveGate, memory limits should be set by setting the appropriate fields in the custom resource spec.

E.g.:
```yaml
activeGate:
  resources:
    limits:
      memory: 1G
```

If you experience problems such as missing events or log spamming as mentioned above, please contact the ActiveGate support, as there is not much we can do from the Operator side.
