### ISSUE TITLE
Dynatrace setup with Kubernetes and Helm - classicFullStack is disabled by default

### ISSUE THREAD

**Issue by thomast1906** [Dynatrace/dynatrace-operator#635]
Attempting to setup using below URL:
https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/set-up-k8s-monitoring-with-helm

In the example values.yaml in the URL above, this value is set to true:
`classicFullStack:
  enabled: true`

If we don't use that values.yaml, the default it uses is false:
https://github.com/Dynatrace/dynatrace-operator/blob/master/config/helm/chart/default/values.yaml 

I can raise a PR to set to the default as true, without this - OneAgent was not running successful in our cluster. 

Or could documentation be updated to reflect the default?  

In reference to `cloudNativeFullStack `/ `applicationMonitoring ` - there is mentions of over rides.

**Comment by chrismuellner** [comment]
WIth the current approach to enable `classicFullStack` you need to set `enabled` to `true`.

If you want to use a different monitoring mode, e.g. `cloudNativeFullStack`, you'd have to set `enabled` to `true` for that mode.

If we enable `classicFullStack` by default (`enabled` to `true`), you'd have to disable that mode before a different mode can be used. So to enable `cloudNativeFullStack` you'd need to set `classicFullStack.enabled=false` and then `cloudNativeFullStack.enabled=true` instead of just enabling `cloudNativeFullStack`.

Since you need to provide values anyway (`apiUrl`, `apiToken`, ...) it's clearer to enable the one monitoring mode you are using directly by passing `classicFullStack.enabled=true`.

**Comment by thomast1906** [comment]
@chrismuellner  could documentation be updated to reference this?

**Comment by chrismuellner** [comment]
Yes, we are in the process of updating the helm instructions to provide sample values files that outline the required changes.
