### ISSUE TITLE
Operator managed resources should be schedulable in a different namespace

### ISSUE THREAD

**Issue by LDL-GH** [Dynatrace/dynatrace-operator#671]
Since I can't reopen a closed ticket I'm creating this new one.

The issue mentioned in https://github.com/Dynatrace/dynatrace-operator/issues/581 has not been resolved as seen by the comment I placed after the issue was closed without confirmation.

Consolidation of info:

When trying to install 0.5.0 the operator does not roll out any oneagent & activegate pods.
There are no error messages in the logs of the dyntrace-operator or dynatrace-webhook pods.

Installing 0.4.2 via oc apply does seem to work but is not preferred.
Main difference that I found was that using oc apply the operator pods are scheduled in the dynatrace namespace as before.
While using operatorHub these pods are scheduled in the openshift-operator namespace.

So I install the operator, it's installed in openshift-operators with AllNamespaces (no other option)
I create a namespace openshift-monitoring-dynatrace (tried dynatrace as well)
I create a dynakube secret containing necessary tokens in this namespace
And finally I create the dynakube in the namespace.

Unfortunately no oneagent/activegate pods are created

**Comment by chrismuellner** [comment]
It sounds like you are creating the secret containing the tokens in a different namespace than the Operator is deployed in.

Do you have any logs of the Operator or the status of the Dynakube as it exists on the cluster?
```
oc logs deployment/dynatrace-operator
oc get dynakube -o yaml
```

**Comment by LDL-GH** [comment]
Hi Chris

I've collected the logs you requested:
[dynakube.txt](https://github.com/Dynatrace/dynatrace-operator/files/8378439/dynakube.txt)
[dynatrace-operator.log](https://github.com/Dynatrace/dynatrace-operator/files/8378440/dynatrace-operator.log)
[dynatrace-webhook.log](https://github.com/Dynatrace/dynatrace-operator/files/8378441/dynatrace-webhook.log)

I've installed the operator using operatorhub with the AllNamespaces option (other option is not available).
This creates the operator and webhook in the openshift-operators namespace.
I've created the dynakube secret in openshift-operators namespace.
I've created a new namespace called openshift-monitoring-dynatrace
I've created the Dynakube CR in openshift-monitoring-dynatrace

This does not work.

The installation documentation still mentions following:
_After creation of the secret add the DynaKube object in the project where the Dynatrace Operator has been deployed, configured to your needs._

This would mean creating the Dynakube CR in openshift-operators.
Doing this would create all resources (activegate, oneagent,...) in the openshift-operators namespace.
This is undesirable, only operators should be created in the openshift-operators namespace.

RedHat describes the AllNamespaces option as following:
_All namespaces on the cluster (default) installs the Operator in the default openshift-operators namespace to watch and be made available to all namespaces in the cluster._

AFAIK this means when installed with this option I should be able to create the Dynakube CR in any namespace I want.

**Comment by ocpvkb** [comment]
I agree to the follwing:
"only operators should be created in the openshift-operators namespace"

Only these options should work:
1. Either everything in a separate Dynatrace namespace (operator+resources)
or 
2. Dynatrace Operator in the "openshift-operators" namespace + Dynatrace resources in a separate Dynatrace namespace

Dynatrace operator+resources in the "openshift-operators" namespace is no option! 
This will break permitted verbs on a set of objects....

That's why we are currently frozen at Version 0.2.2. :-(

**Comment by mreider** [comment]
Our Operator team raised this issue with product management today in an internal meeting. 

From a product perspective, the following things are clear:

1. Dynatrace supports OLM and will continue to do so.
2. Our new Cloud-Native Injection does not currently support OLM
3. We will address this deficiency in order to stand by our OLM support

The obvious question, in regards to number 3, is "what's the timeframe?" At this point I cannot provide an answer as the item has no estimate in JIRA. We will put an estimate on it in the next few months. Importantly, we will not end support for your current OLM deployment (0.2.2) before we implement a solution.

**Comment by mreider** [comment]
Here's an update in a Google doc with good news regarding this Github Issue 😊.

https://docs.google.com/document/d/1zLBR8Zsw8QNAd9BdsHtnraCf4QMXRahz6ohdelPntWc/edit?usp=sharing

**Comment by luhi-DT** [comment]
Hi, 

with 0.9.0 we have released the option to install the Dynatrace Operator to the dynatrace namespace via OperatorHub. 
However if you still feel that this does not satisfy you needs please create a feature requests in the [Dynatrace community](https://community.dynatrace.com/) rather than Github. This helps our team consolidate, rank, and prioritize important input like yours.

Please search for similar requests, collaborate, and ask questions using the link above. Remember to add the labels "kubernetes" and "dynatrace-operator" to help get the attention you deserve.

Thanks for your help!
